version: '3'

services:
  website:
    container_name: Nginx
    image: nginx:latest
    volumes:
      - ./Nginx/html:/usr/share/nginx/html
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - backend

  rest-api:
    container_name: REST-API
    hostname: personnalwebsite.api
    build: ./API
    volumes:                     
      - ./API/app:/app         
    ports:
      - '5000:80'
    networks:
      - backend

  sql-server:
    container_name: SqlServer-2022
    hostname: SQLServer2022
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'YourStrong@Passw0rd' 
    ports:
      - '1433:1433'
    volumes:
      - ./DB:/var/opt/mssql/data
    user: '${UID}:${GID}'
    networks:
      - backend
    entrypoint:
      - /bin/bash
      - -c
    command: >
      "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong@Passw0rd' -d master -i /var/opt/mssql/data/init.sql & /opt/mssql/bin/sqlservr"

networks:
  backend: 